In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data Tugas.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Andi' 80 80.0 90.0 80.0 28]
 ['Ari' 78 89.0 80.0 80.0 30]
 ['Della' 90 nan 85.0 88.0 32]
 ['Kristi' 74 87.0 88.0 nan 30]
 ['Sari ' 82 82.0 90.0 nan 31]
 ['Bayu' 96 87.0 nan 87.0 29]
 ['Ambian' 78 78.0 88.0 86.0 30]
 ['Rusdi' 78 79.0 82.0 90.0 27]
 ['Dian' 78 nan 78.0 85.0 26]
 ['Wawan' 88 85.0 84.0 82.0 28]]


In [ ]:
print(y)

['Baik' 'Baik' 'Sangat Baik' 'Baik' 'Baik' 'Sangat Baik' 'Baik' 'Baik'
 'Baik' 'Baik']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:6])
x[:, 1:6] = imputer.transform(x[:, 1:6])

In [ ]:
print(x)

[['Andi' 80.0 80.0 90.0 80.0 28.0]
 ['Ari' 78.0 89.0 80.0 80.0 30.0]
 ['Della' 90.0 83.375 85.0 88.0 32.0]
 ['Kristi' 74.0 87.0 88.0 84.75 30.0]
 ['Sari ' 82.0 82.0 90.0 84.75 31.0]
 ['Bayu' 96.0 87.0 85.0 87.0 29.0]
 ['Ambian' 78.0 78.0 88.0 86.0 30.0]
 ['Rusdi' 78.0 79.0 82.0 90.0 27.0]
 ['Dian' 78.0 83.375 78.0 85.0 26.0]
 ['Wawan' 88.0 85.0 84.0 82.0 28.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 80.0 90.0 80.0 28.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 78.0 89.0 80.0 80.0 30.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 90.0 83.375 85.0 88.0 32.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 74.0 87.0 88.0 84.75 30.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 82.0 82.0 90.0 84.75 31.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 96.0 87.0 85.0 87.0 29.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 78.0 78.0 88.0 86.0 30.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 78.0 79.0 82.0 90.0 27.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 78.0 83.375 78.0 85.0 26.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 88.0 85.0 84.0 82.0 28.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 1 0 0 1 0 0 0 0]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 78.0 78.0 88.0 86.0 30.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 82.0 82.0 90.0 84.75 31.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 80.0 80.0 90.0 80.0 28.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 74.0 87.0 88.0 84.75 30.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 78.0 89.0 80.0 80.0 30.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 78.0 79.0 82.0 90.0 27.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 78.0 83.375 78.0 85.0 26.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 96.0 87.0 85.0 87.0 29.0]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 90.0 83.375 85.0 88.0 32.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 88.0 85.0 84.0 82.0 28.0]]


In [ ]:
print(y_train)

[0 0 0 0 0 0 0 1]


In [ ]:
print(y_test)

[1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 6:] = sc.fit_transform(x_train[:, 6:])
x_test[:, 6:] = sc.transform(x_test[:, 6:])

In [ ]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 -0.4016096644512494 -1.3415110019159864
  0.6620247118789144 0.4167618376277693 0.6964409092807231]
 [0.0 0.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  2.6457513110645903 0.0 0.24096579867074966 -0.3039677496788489
  1.1225636418816374 0.01984580179179854 1.3154994953080326]
 [0.0 1.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 -0.08032193289024989 -0.8227393757974176
  1.1225636418816374 -1.4884351343848905 -0.5416762627738958]
 [0.0 0.0 0.0 0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272
  -0.3779644730092272 0.0 -1.0441851275732486 0.992961315617573
  0.6620247118789144 0.01984580179179854 0.6964409092807231]
 [0.0 0.0 1.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 -0.4016096644512494 1.5117329417361418
  -1.1801310081319778 -1.4884351343848905 0.6964409092807231]
 [0.0 0.0 0.0 0.0 0.0 0.0 -0.377964473

In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 0.0 1.5261167249147478 0.052687743277667135
  -0.02878368312517019 1.0518274949653226 1.934558081335342]
 [0.0 0.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.3779644730092272 1.0 1.2048289933537484 0.47418968949900425
  -0.25905314812653174 -0.8533694770473372 -0.5416762627738958]]
